Backend/Concert/urls.py
from django.contrib import admin # type: ignore
from django.urls import path          # type: ignore
from django.conf import settings    # type: ignore
from django.conf.urls.static import static  # type: ignore
from Ticketsales.views import ConcertListView , LocationView , TimeView , Concertdetail
urlpatterns = [
    path('admin/', admin.site.urls),
    path('Ticketsales/Concert/list',ConcertListView),
    path('Ticketsales/location/list',LocationView),
    path('Ticketsales/time/list',TimeView),
    path('Ticketsales/Concert/<int:concert_id>', Concertdetail)
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/Ticketsales/models.py
from django.db import models # type: ignore

class ConcertModel(models.Model):

    class Meta:
         verbose_name ="کنسرت"
         verbose_name_plural = "کنسرت"



    Name = models.CharField(max_length=200, verbose_name= "نام کنسرت")
    SingerName = models.CharField(max_length=150 ,verbose_name="نام خواننده")
    lenght = models.IntegerField(verbose_name=" مدت زمان")
    poster = models.ImageField(upload_to= "ConcertImage" , null= True,verbose_name = "پوستر")

    def __str__(self) :
        return self.SingerName
    


class LocationModel(models.Model):

    class Meta:
        verbose_name="محل برگزاری"
        verbose_name_plural="محل برگزاری"


    Name = models.CharField(max_length=100,verbose_name="مکان برگزاری")
    Address = models.CharField(max_length=500 , default= "برج میلاد",verbose_name="ادرس") 
    phone = models.CharField(max_length=11 , null= True ,verbose_name="شماره تماس")
    Capacity = models.IntegerField()

 
    def __str__(self):
        return self.Name
    

class TimeModel(models.Model):
   
    class Meta:
         verbose_name="زمان برگزاری"
         verbose_name_plural="زمان برگزاری"


    ConcertModel = models.ForeignKey("ConcertModel", on_delete= models.PROTECT,verbose_name="نام خواننده")
    LocationModel = models.ForeignKey( "LocationModel" , on_delete=models.PROTECT,verbose_name="مکان کنسرت")
    StartDatetime = models.DateTimeField(verbose_name = "تاریخ")
    Seats = models.IntegerField(verbose_name='تعداد صندلی')

    start =1
    End = 2
    Cancle = 3
    Sales = 4
    status_choises = (('start','فروش بلیط شروع شده است'),
                     ('end','فروش بلیط تمام شده است' ),
                     ("Cancle", "این سانس کنسل  شده است"),
                     ("Sales","در حال فروش بلیط"),
                     )



    Status = models.CharField(choices=status_choises , null=True , verbose_name="وضعیت" , max_length=50)


    def __str__(self) :
        return f"{self.StartDatetime} - {self.ConcertModel}"
    




class ProfileModel(models.Model):
        

        class Meta:
             verbose_name="شرکت کنندگان"
             verbose_name_plural="شرکت کنندگان"


        Name = models.CharField(max_length=100,verbose_name="نام")
        Family = models.CharField(max_length=100,verbose_name="نام خانوادگی")
        ProfileImage = models.ImageField(upload_to= "ProfileImage/" , null= True ,verbose_name = "عکس پروفایل")



        Man = 1
        Women = 2
        status_choises = (("Man", "مرد"), ("Women", "زن"))



        Gender = models.IntegerField(choices=status_choises ,verbose_name = "جنسیت")

        def __str__(self) :
            return "Full.Name:{} {} " .format( 'Name' ,'Family')
        


class TicketModel(models.Model):
        
        class Meta:
             verbose_name=" بلیط"
             verbose_name_plural=" بلیط"


        ProfileModel = models.ForeignKey("ProfileModel",on_delete=models.PROTECT,verbose_name="پروفایل")
        timeModel = models.ForeignKey("timeModel",on_delete=models.PROTECT,verbose_name="زمان")


        Name = models.CharField(max_length=100,verbose_name="نوع بلیط")
        price = models.IntegerField(verbose_name="قیمت")
        TicketImage = models.ImageField(upload_to= "TicketImages/", null= True,verbose_name="تصویر بلیط")




        def __str__(self) -> str:
            return "TicketInfo: Profile:{} ConcertInfo: {}".format( TimeModel.__str__())

Backend/Ticketsales/views.py
from django.shortcuts import render #type:ignore
from .models import ConcertModel ,LocationModel  , TimeModel
# Create your views here.


def ConcertListView(request):
    concerts= ConcertModel.objects.all()

    context = {
        "concert":concerts
    }



    return render(request,"Ticketsales/concert.html",context)





def LocationView(request):
    locations= LocationModel.objects.all()

    context = {
        "location":locations,
    }



    return render(request,"Ticketsales/location.html",context)




def Concertdetail(request , concert_id):
    

    concert = ConcertModel.objects.get(pk=concert_id)
    


    context = {
        "Concertdetails" : concert
    }

    return render(request, "Ticketsales/concertdetail.html" , context)











def TimeView(request):

    times = TimeModel.objects.all()

    context = {
        "times" : times,

    }


    return render(request , "Ticketsales/time.html" , context)

Backend/Ticketsales/templates/Ticketsales/concert.html
{% extends "Ticketsales/layout.html" %}

{% block titlepage %} 
    لیست کنسرت ها
{% endblock%}

{% block mainContent %}
    {% if concertlist %}

    <form action="" method="GET">
        {{ searchForm }}

        <button type="submit" class="btn btn-success">جستجو</button>
    </form>

        {% for concert in concertlist %}
           
            <div class="col-md-2">
                <a href="/Ticketsales/concert/{{ concert.id }}">
                    <div class="imageBox">
                        <img src="{{ Concert.poster.url }}">
                        {{ concert  }}
                    </div>
                </a>
            </div>
        {% endfor %}
    {% endif %}

{% endblock%}
               
           

Backend/Ticketsales/templates/Ticketsales/concertdetail.html
{% extends "Ticketsales/layout.html" %}

{% block titlepage %} 
    جزییات {{ concertdetail.Name }}
{% endblock%}

{% block mainContent %}
   
    <div class="col-md-10">
            
       <h3>نام کنسرت : {{concertdetail.Name }}</h3>
       <h3>خواننده کنسرت : {{concertdetail.SingerName }}</h3>
       <h3>مدت زمان کنسرت : {{concertdetail.lenght }}</h3>


    </div>
    <div class="col-md-2">
        
            <div class="imageBox">
                <img src="{{ concertdetail.poster.url }}">
            </div>
            <a href="/ticketsales/concertEdit/{{ concertdetail.id }}" class="btn btn-success" >ویرایش</a>
    </div>

{% endblock%}

Backend/Ticketsales/templates/Ticketsales/layout.html
{% load static %}
<!DOCTYPE html>
<html dir="rtl">
    <head>
        <title>سامانه فروش بلیط کنسرت</title>
       
        <link rel="stylesheet" type="text/css" href="{% static 'ticketsales/css/bootstrap.css' %} " >
        <link rel="stylesheet" type="text/css" href="{% static 'ticketsales/css/fontawesome.css' %} " >
        <link rel="stylesheet" type="text/css" href="{% static 'ticketsales/css/style.css' %} " >
        
        <style>
            @font-face{
                font-family: 'IranSanse';
                src: local('IranSanse'),
                url('{% static "ticketsales/fonts/eot/IRANSansWeb.eot" %}') format('eot'),
                url('{% static "ticketsales/fonts/ttf/IRANSansWeb.ttf" %}') format('ttf'),
                url('{% static "ticketsales/fonts/woff/IRANSansWeb.woff" %}') format('woff'),
                url('{% static "ticketsales/fonts/woff2/IRANSansWeb.woff2" %}') format('woff2');
            }
        </style>>


    </head>
    <body>
             
        <div class="container">
            <div class="row box">
               
                <h1>{% block titlepage %} {% endblock%}</h1>
                <ul class="btnul">
                    
                    {% if user.is_authenticated %}
                        <li><a class="btn btn-success" href="/accounts/profile">پروفایل</a></li>
                        <li><a class="btn btn-danger" href="/accounts/logout">خروج</a></li>

                    {% else %}
                        <li><a class="btn btn-success" href="/accounts/login">ورود</a></li>
                        <li><a class="btn btn-danger" href="/accounts/profileRegister">ثبت نام</a></li>
                    {% endif %}
                   
                   
                    
                    <li><a class="btn btn-primary" href="/Ticketsales/time/list"> مشاهده سانس های کنسرت</a></li>
                    <li><a class="btn default" href="/Ticketsales/Concert/list">صفحه اصلی</a></li>
                    <li><a class="btn btn-danger"  href="/Ticketsales/location/list">اطلاعات محل</a></li>
                </ul>
            </div>
          
            <div class="row">
                
                  {% block mainContent %}{% endblock%}
               
            </div>
        </div>
          
    </body>
    <script src="{% static 'ticketsales/js/jquery-3.6.0.min.js' %} " ></script>
    <script src="{% static 'ticketsales/js/bootstrap.bundle.js' %} " ></script>
    <script src="{% static 'ticketsales/js/fontawesome.js' %} " ></script>
    <script src="{% static 'ticketsales/js/main.js' %} " ></script>
</html>

Backend/Ticketsales/templates/Ticketsales/location.html
{% extends "Ticketsales/layout.html" %}

{% block titlepage %} 
    لیست مکان های برگزاری کنسرت 
{% endblock%}

{% block mainContent %}

    <div class="row locationHeader">
        <div class="col-md-3">
            <h3>نام سالن</h3>
        </div>
        <div class="col-md-9">
        <h3>آدرس</h3>
        </div>
    </div>

    {% if location %}
        {% for location in location %}
          
            <div class="row location">
                <div class="col-md-3">
                    {{ location.Name }}
                </div>
                <div class="col-md-9">
                    {{ location.Address }}
                </div>
               
            </div>
           
        {% endfor %}
    {% endif %}

{% endblock%}
               
           

Backend/Ticketsales/templates/Ticketsales/time.html
{% extends "Ticketsales/layout.html" %}

{% block titlepage %} 
    لیست سانس ها
{% endblock%}

{% block mainContent %}
    {% if time %}
        {% for time in time%}
            <div class="col-md-2">
                <a>
                    <div class="timeBox">
                       <h2> {{ time.concertModel.Name  }}</h2>
                       <p>{{ time.concertModel.SingerName  }}</p>
                       <p>{{ time.locationModel.Name  }}</p>
                       <p>{{ time.get_jalai_date }}</p>
                       <div 
                       
                        class="
                        
                        {% if time.Status == time.Start %}
                            btn btn-success

                        {% elif  time.Status == time.End %}
                            btn btn-danger

                         {% elif  time.Status == time.Cancle %}
                            btn default

                        {% elif  time.Status == time.Sales %}
                            btn btn-primary

                        {% endif %}
                        
                        ">

                           {{ time.get_Status_display}}
                       </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    {% endif %}

{% endblock%}
               